json.id home.id
json.description home.description
json.year_built home.year_built
json.square_feet home.square_feet
json.bedrooms home.bedrooms
json.bathrooms home.bathrooms
json.floors home.floors
json.availability home.availability
json.address home.address
json.price home.price